trigger:
  branches:
    exclude:
      - master

# schedules:
# - cron: '0 13 * * 1-5'
#   displayName: 1300 Mo through Fri
#   branches:
#     include:
#     - master


pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: 'Install pytest'
  inputs:
    targetType: 'inline'
    script: |
      pip install --upgrade pip
      pip install pytest pytest-xdist allure-pytest
- task: Bash@3
  displayName: 'Install allurectl'
  inputs:
    targetType: 'inline'
    script: |
      curl -L https://github.com/cheshi-mantu/allurectl-local-builds/releases/latest/download/allurectl_linux_amd64 -o ./allurectl
      chmod +x ./allurectl

- script: |
    ./allurectl watch -- pytest $(TESTS_TYPE) || true
    printenv | grep "ALLURE_"
    printenv | grep "TEST_"
    printenv | grep "AZURE_"
    echo "All variables"
    printenv
  displayName: 'running pytest tests'
  env:
    ALLURE_ENDPOINT: https://demo.testops.cloud
    ALLURE_PROJECT_ID: $(ALLURE_PROJECT_ID)
    ALLURE_TOKEN: $(ALLURE_TOKEN)
    ALLURE_RESULTS: $(ALLURE_RESULTS)
    ALLURE_LAUNCH_NAME: "$(Build.DefinitionName)-$(Build.BuildNumber)"
    TEST_BRANCH: $(Build.SourceBranchName)
    ALLURE_LAUNCH_TAGS: "$(env | cut -d= -f1)"
    AZURE_BROWSER: $(AZURE_BROWSER)
    AZURE_HOST: $(AZURE_HOST)
    TESTS_SUCCESS: $(TESTS_SUCCESS)